var express = require('express')
    , router = express.Router()
    , ping = require('./api/ping')
    , jmeter = require('./api/exec/jmeter.api')
    , artillery = require('./api/exec/artillery.api')
    , selenium = require('./api/exec/selenium.api')
    , users = require('./api/user/users.api')
    , componentApi = require('./api/component/component.api')
    , componentsApi = require('./api/component/components.api')
    , componentTypesApi = require('./api/component/component.types.api')
    , graphsApi = require('./api/dashboard/graph.api')
    , graphApi = require('./api/dashboard/graph.types.api')
    , graphInstancesApi = require('./api/dashboard/graph.instances.api')
    , graphInstanceApi = require('./api/dashboard/graph.instance.api')
    , environmentsApi = require('./api/environment/environment.api')
    , groupApi = require('./api/component/group.api')
    , groupsApi = require('./api/component/groups.api')
    , projecsApi = require('./api/project/project.api')
    , dashboardTypeApi = require('./api/dashboard/dashboard.types.api')
    , dashboardApi = require('./api/dashboard/dashboard.api')
    , dashboardsApi = require('./api/dashboard/dashboards.api')
    , testApi = require('./api/test/test.api')
    , testsApi = require('./api/test/tests.api')
    , testExecutionApi = require('./api/test/test.execution.api')
    , testExecutionsApi = require('./api/test/test.executions.api')
    , accessibilityApi = require('./api/exec/accessibility.api')
    , elasticSearchApi = require('./api/elasticsearch/es.api')
    , initFilter = require('../src/common/init.filter');

var restVersionV1 = '/rest/api/v1/perf';

router.all(restVersionV1 + '*', initFilter.initValidation);

router.use(restVersionV1 + '/ping', ping);
router.use(restVersionV1 + '/jmeter', jmeter);
router.use(restVersionV1 + '/selenium', selenium);
router.use(restVersionV1 + '/artillery', artillery);
router.use(restVersionV1 + '/accessibility', accessibilityApi);
router.use(restVersionV1 + '/user', users);
router.use(restVersionV1 + '/component', componentApi);
router.use(restVersionV1 + '/comp', componentTypesApi);
router.use(restVersionV1 + '/components', componentsApi);
router.use(restVersionV1 + '/graph', graphApi);
router.use(restVersionV1 + '/graphs', graphsApi);
router.use(restVersionV1 + '/dashboard/graph/instances', graphInstancesApi);
router.use(restVersionV1 + '/dashboard/graph/instance', graphInstanceApi);
router.use(restVersionV1 + '/environment', environmentsApi);
router.use(restVersionV1 + '/group', groupApi);
router.use(restVersionV1 + '/groups', groupsApi);
router.use(restVersionV1 + '/project', projecsApi);
router.use(restVersionV1 + '/dashboardtype', dashboardTypeApi);
router.use(restVersionV1 + '/dashboard', dashboardApi);
router.use(restVersionV1 + '/dashboards', dashboardsApi);
router.use(restVersionV1 + '/test', testApi);
router.use(restVersionV1 + '/tests', testsApi);
router.use(restVersionV1 + '/execution/test', testExecutionApi);
router.use(restVersionV1 + '/execution/tests', testExecutionsApi);
router.use(restVersionV1 + '/es', elasticSearchApi);

module.exports = router;
